# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAnalyze < Formula
  desc "git commit log analyze"
  homepage "https://github.com/iwata-n/git-analyze"
  version "1.0.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iwata-n/git-analyze/releases/download/v1.0.0/git-analyze_1.0.0_darwin_amd64.tar.gz"
      sha256 "d74f7c2a64db06f5e3a6e9ecf91301b31f91750cb6fe89a668a768c8ce93c986"
    end
    if Hardware::CPU.arm?
      url "https://github.com/iwata-n/git-analyze/releases/download/v1.0.0/git-analyze_1.0.0_darwin_arm64.tar.gz"
      sha256 "445b09252f1a5a061f24c981b3c1d0c65a5038734a6d1c365400bddea1f07d8d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/iwata-n/git-analyze/releases/download/v1.0.0/git-analyze_1.0.0_linux_amd64.tar.gz"
      sha256 "76b036ffa56c333f352a654e61c85b73594a85e06c466a6ec238e939b2f81727"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/iwata-n/git-analyze/releases/download/v1.0.0/git-analyze_1.0.0_linux_armv6.tar.gz"
      sha256 "d45d391fd64a08d674a70ba0175a7c1ff722239e7363b4b71d3217627cfebc3a"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iwata-n/git-analyze/releases/download/v1.0.0/git-analyze_1.0.0_linux_arm64.tar.gz"
      sha256 "cdd2dc8ef85eef05adc6cb68aca7914a42ea8060029721c1fbd1aa28e77a1bcf"
    end
  end

  def install
    bin.install "git-analyze"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
